services:
# postgres db setup
  postgres:
    container_name: postgres-sql-bsc
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: book_social_club
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - bound-bsc
    restart: unless-stopped

# Mail dev server setup
  mail-dev:
    container_name: mail-dev-bsc
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

# Springboot backend book social clund
  bsc-api:
    container_name: bsc-api
    image: bsc/bsc:0.0.1
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#      - DB_URL=jdbc:postgresql://postgres-sql-bsc:5432/bound_social_club
    ports:
      - 8088:8088
    networks:
      - bound-bsc
    depends_on:
      - postgres

# Networks - local
networks:
  bound-bsc:
    driver: bridge
# Volumes - local storage
volumes:
  postgres:
    driver: local

